const fs=require('fs'),vm=require('vm');
function run(test){const elements={};const ctx=new Proxy({measureText:()=>({width:50})},{get:(t,k)=>t[k]||(()=>{})});const el=s=>elements[s]??=(s==='canvas'?{getContext:()=>ctx}:{style:{},children:[],appendChild(child){this.children.push(child)},setAttribute(k,v){this[k]=v},focus(){},textContent:'',innerHTML:''});const sandbox={document:{querySelector:el,createElement:()=>({style:{},setAttribute(k,v){this[k]=v}}),querySelectorAll:selector=>selector==='.swatch'?el('#swatches').children:[]},innerWidth:1200,innerHeight:800,devicePixelRatio:1,addEventListener(){},requestAnimationFrame(){},location:{reload(){}},console};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('work/game-check.js','utf8'),sandbox);vm.runInContext('function assert(x,m){if(!x)throw Error(m)}'+test,sandbox)}
run(`draw();let layers=faces.map(f=>f.layer);assert(layers.every((v,i)=>i===0||v>=layers[i-1]),'render layer order');const blanket=faces.filter(f=>f.layer===2);assert(blanket.length===3&&blanket.every(f=>f.points.every(p=>p[1]>=.06)),'raised blanket');assert(faces.filter(f=>f.layer===3).every(f=>f.points.every(p=>p[1]>.12)),'checks above blanket');player.x=0;player.z=-2;interact();assert(!finished&&confirmingSit&&!player.seated,'confirmation before ending');$('#confirm-sit').onclick();assert(finished&&!won&&player.seated,'lose and sit');assert($('#speaker').textContent.includes('lose'),'lose popup');let x=player.x;keys.d=true;tick(50);assert(player.x===x,'movement stopped after ending');close();assert($('#dialog').style.display==='block','ending stays visible');`);
run(`for(const c of cats){player.x=c.x;player.z=c.z;interact();assert(c.asked,'request');close();const i=items.find(i=>i.name===c.item);player.x=i.x;player.z=i.z;interact();assert(i.held,'collect');close();player.x=c.x;player.z=c.z;interact();assert(c.done,'deliver');close()}cats.forEach(c=>{c.x=0;c.z=-2});player.x=0;player.z=-2;interact();assert(!finished&&confirmingSit&&!player.seated,'confirmation before ending');$('#confirm-sit').onclick();assert(finished&&won&&player.seated,'win takes priority over nearby NPC');assert($('#speaker').textContent.includes('win'),'win popup');assert($('#close').textContent==='Play again','restart offered');`);
run(`cats[0].done=true;player.x=1;player.z=-2.5;interact();assert(!finished&&confirmingSit&&!player.seated,'confirmation before ending');$('#confirm-sit').onclick();assert(finished&&!won,'partial tasks lose');`);
run(`assert($("#swatches").children.length===6,'six color choices');const swatch=$("#swatches").children[5];swatch.onclick();assert(player.color==='#b2a1c9','fur color updates');assert($("#color-name").textContent==='Lilac','color label updates');assert(swatch['aria-pressed']==='true'&&$("#swatches").children[0]['aria-pressed']==='false','selected swatch updates');draw();`);
run(`player.x=0;player.z=-2;interact();assert(confirmingSit&&!finished,'asks before losing');assert($('#words').textContent.includes('you will lose'),'unfinished task warning');close();assert(!confirmingSit&&!finished&&!player.seated,'cancel preserves game');$('#confirm-sit').onclick();assert(!finished,'stale confirmation ignored');interact();interact();assert(!finished&&!confirmingSit,'E cancels rather than confirms');cats.forEach(c=>c.done=true);interact();assert($('#words').textContent.includes('celebrate your win'),'ready message');`);
run(`const layouts=new Set(),assignments=new Set();for(let j=0;j<100;j++){randomizeGame();assert(new Set(cats.map(c=>c.item)).size===3,'unique requests');assert(new Set(items.map(i=>i.x+','+i.z)).size===3,'unique positions');assert(items.every(i=>i.hint&&!atItemBlanket(i)),'safe hinted positions');layouts.add(items.map(i=>i.x+','+i.z).join('|'));assignments.add(cats.map(c=>c.item).join('|'));}function atItemBlanket(i){return Math.abs(i.x)<=1.25&&Math.abs(i.z+2)<=1}assert(layouts.size>1&&assignments.size>1,'layouts and requests vary');const c=cats[0];player.x=c.x;player.z=c.z;interact();const item=items.find(i=>i.name===c.item);assert($('#words').textContent.includes(item.hint),'dialogue matches randomized location');`);
console.log('PASS: randomized requests and locations, picnic confirmation and cancellation, color picker, raised blanket layers, incomplete/partial loss, completed win, picnic priority, seated ending, movement lock, replay button');



